name: financial_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.6
  email_validator: "^2.1.17"
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  path: ^1.9.1
  provider: ^6.1.5+1
  sizer: ^3.1.3
  sqflite: ^2.4.2
  animated_search_bar: ^2.8.0
  syncfusion_flutter_charts: ^31.1.23

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - .env
